---
- name: add specified users to audio and video groups
  user: 
    name: "{{ item }}"
    groups: 'audio,video'
    append: yes
  with_items: "{{ audio_users }}"

- name: install audio packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - linux-sound-base
    - alsa-base
    - alsa-utils
    - linux-image-{{ ansible_kernel }}
    - linux-image-extra-{{ ansible_kernel }}
    - libasound2
