---
# Require Ubuntu 14.04
dist: trusty

# Require Docker
services:
  - docker

language: python

python:
  # Specify Python version
  - '3.6'

install:
  # Install lint tools.
  - gem install rubocop

  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  # Run build script
  - .travis/build.sh

branches:
  only:
    - master
    - develop
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

env:
  global:
    # GIT_USERNAME
    - secure: ZnCqgsXRyxVoA8YPNgqRxbzpCitQYehAyvnDj8hEJ/KK6O4WBAgNnnNnMaLGbFopgrcEDLyo4e+3Kju+BL3aXczPDbBK9sfktmxWSvGFynu/XouuB0ecFlnBxANS+LaYDf5fypK9S6aOECy5Kev/+VosZwe/RyKK8H+1T9a20Ee8hOtyu4KrSfg2YdF0fw9Wgdo4FslWw0lEhEHeS27CltMRkAhg86CbxIkhdvYpQmbJw5wPwY5GzwEAWlpbngEqvdaCKw5Dt2pKG7RYnCw5F0vNfswnvEOa5nHWkpOASJtMA9isVM0kr1jVr2uXd5UhgjffL99gWwS9QVsqZCcSclFgktl9l+0bDhDKXiHrnapMJVKMT/dBGeAvva4Wkq9J9Q6n6B5U+3NDSibS5S03ri7cHvbj88waHiXHsjSCXCZvrFxp4fSx9Wh29F9ueX8fpZhgGqZ5j43Rz4WAhqigA1Z5U3C/u8AGCe0Pi/1JQkuGxBb3pzCPljk9toryF/FJYuH/n/yzHWoYPcWcsYan4SRdqJS+hVcKYapluRf6so2ZZQ01o4k8AqHJsTGqDHPEjGCAqvnWENHGZ5TbyogjAJqP7WxI6QHH1EZv9cw1CCnWQoQE2Q6qzU/NrltfcEOWlpoX+/Dsd2FNAB4pLqqhBWtbgJP0HwiB++WO6O3iBaU=
    # GIT_PASSWORD
    - secure: RAAR37WWE8UMLRdHfjRhmM6x0f5/rWGrUfD75F76BXIwNM5kSUJdGR15edQZzNnGmm+0EhKYHDRyA5HV2OytQ4WkU55azNDrDxSRmUKvZ73tWJehGIl6u0z6/Pmqyt2VB5fYinsDiJJyAA9j50l9cg+Qb1+1BIzrsRrZCpBNH7aSnufAFuuUmp/+oXNidVwu1Mdmw+ab6KuVs56bErw0cjmJNQiup2hj6sQuGO0yF6jmU+8r8O9Zj9qnhq8N5tcdskua4cSrDdeEb/ulau48NlwX/mWUnzMB+QgyxJGZxMOj/HOU6EYvdg4DrnQjBZg6eGQ6omdRU2jvTs9i2/xSBlkl66faH/oIW2tICc2kQOFDcxrI1OSBI9aMFcx1r9ZA8MJH5T2anoRbxOA3kKfZMkBN8h+FxkhGsDcSuMSEIY7Y2Y54LgiSGu1dN0XHby492NVW3pPOvtQnD4f0yGdCESrl9Cq59++XenxRxXWnKE6TTorF4vXk4t43DgPqYjZYhsWYT4a1f8iAnbJVvqQxfP85GgICjYC75bjG+41LWa7EJZDLAjGOGo9kN9axRtb5rWs0aHLrD9rNY1J/bB2HfSKIsxLlfW6ASlOQzwEWAN6Vre1tpJWJ/1S7sHVp5xwIdjHy6PaOpgWS2xJ8PIrki32lA3KBefndETr1OmEnIJw=
