---
idea_default_jdk_classpath:
  - /jre/lib/charsets.jar
  - /jre/lib/ext/cldrdata.jar
  - /jre/lib/ext/dnsns.jar
  - /jre/lib/ext/icedtea-sound.jar
  - /jre/lib/ext/jaccess.jar
  - /jre/lib/ext/java-atk-wrapper.jar
  - /jre/lib/ext/localedata.jar
  - /jre/lib/ext/nashorn.jar
  - /jre/lib/ext/sunec.jar
  - /jre/lib/ext/sunjce_provider.jar
  - /jre/lib/ext/sunpkcs11.jar
  - /jre/lib/ext/zipfs.jar
  - /jre/lib/jce.jar
  - /jre/lib/jsse.jar
  - /jre/lib/management-agent.jar
  - /jre/lib/resources.jar
  - /jre/lib/rt.jar
idea_default_language_level: JDK_1_8
