# path for ansible to store downloaded or templated data
local_ansible_data_path: '/usr/local/src/ansible/data'
remote_ansible_data_path: "{{ local_ansible_data_path }}"

# filename of Maven Notifier redistributable package
maven_notifier_redis_filename: "maven-notifier-{{ maven_notifier_version }}-shaded.jar"
