---
# Configure DockbarX launcher
- name: install gconf2
  apt:
    name: gconf2
    state: present
- name: add launchers to dockbarx
  shell: |
    new_launcher='{{ item }}'

    # Get the current list of launchers
    existing_launchers=$(gconftool-2 --get /apps/dockbarx/launchers 2> /dev/null \
      | grep --color=never '^\[' || echo "[]")

    # If the launcher is already in the list exit successfully here
    echo "$existing_launchers" | grep -P "[\[,]${new_launcher}[\],]" && exit 0

    # Append the new launcher to the end of the list
    new_launchers=$(echo "$existing_launchers" | sed "s:\]$:,${new_launcher}\]:" | sed "s:^\[,:\[:")

    # Update the list of launchers
    gconftool-2 --type list --list-type=string \
      --set /apps/dockbarx/launchers "$new_launchers" \
    || exit 1
  with_items: "{{ launchers }}"
  become: yes
  become_method: sudo
  become_user: vagrant
