---
- name: add unison ppa
  apt_repository: repo='ppa:john-freeman/unison'
- name: install unison
  apt: name=unison state=present
- name: write unison systemd configration
  template: >
    src=unison.service
    dest=/etc/systemd/system/unison.service
- name: create vagrant .unison directory
  file: >
    path=/home/vagrant/.unison/
    state=directory
    owner=vagrant
    group=vagrant
- name: write unison vagrant profile
  template: >
    src=vagrant.prf
    dest=/home/vagrant/.unison/vagrant.prf
    owner=vagrant
    group=vagrant
- name: sync missing files from host to client
  shell: >
    /usr/bin/unison vagrant
    -dumbtty
    -nodeletion=/home/vagrant
    -noupdate=/home/vagrant
    -prefer=/vagrant/home
    -force=/vagrant/home
    -ignorearchives
    -logfile=/home/vagrant/.unison/init1.log
    &> /home/vagrant/.unison/init1.out
  register: command_result
  failed_when: command_result.rc > 1
  become: yes
  become_method: sudo
  become_user: vagrant
- name: create missing includeDirectories
  file: >
    path=/home/vagrant/{{ item }}
    state=directory
    owner=vagrant
    group=vagrant
  with_items: "{{includeDirectories}}"
- name: create missing includeFiles
  copy: >
    content=""
    dest=/home/vagrant/{{ item }}
    force=no
    owner=vagrant
    group=vagrant
  with_items: "{{includeFiles}}"
- name: sync missing files from client to host
  shell: >
    /usr/bin/unison vagrant
    -dumbtty
    -nodeletion=/vagrant/home
    -noupdate=/vagrant/home
    -prefer=/home/vagrant
    -force=/home/vagrant
    -ignorearchives
    -logfile=/home/vagrant/.unison/init2.log
    &> /home/vagrant/.unison/init2.out
  register: command_result
  failed_when: command_result.rc > 1
  become: yes
  become_method: sudo
  become_user: vagrant
- name: sync file changes from host to client
  shell: >
    /usr/bin/unison vagrant
    -dumbtty
    -prefer=/vagrant/home
    -force=/vagrant/home
    -nodeletion=/home/vagrant
    -ignorearchives
    -logfile=/home/vagrant/.unison/init3.log
    &> /home/vagrant/.unison/init3.out
  register: command_result
  failed_when: command_result.rc > 1
  become: yes
  become_method: sudo
  become_user: vagrant
- name: update unison archives
  shell: >
    /usr/bin/unison vagrant
    -dumbtty
    -prefer=/vagrant/home
    -logfile=/home/vagrant/.unison/init4.log
    &> /home/vagrant/.unison/init4.out
  register: command_result
  failed_when: command_result.rc > 1
  become: yes
  become_method: sudo
  become_user: vagrant
- name: add unison service to default run level and start
  service: name=unison enabled=yes state=started
